version: '3.7'

services:
  dnd-village-api:
    image: dnd-village-api
    build:
      context: $PWD
    ports:
      - 8080:5000
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:11.13
    environment: 
      POSTGRES_DB: village_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
