# Generated by Django 3.2.6 on 2021-08-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_api", "0001_create_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="family_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
