# Generated by Django 3.2.6 on 2021-08-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location_type', models.CharField(choices=[('Village', 'V'), ('City', 'C'), ('Dungeon', 'D')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='village_api.location')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='village_api.family'),
        ),
    ]
