# Generated by Django 3.2.6 on 2021-08-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_api", "0002_family_family_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Familial", "FAMILY"),
                            ("Romantic", "ROMANTIC"),
                            ("Friends", "FRIENDSHIP"),
                            ("Enemies", "ENEMY"),
                            ("Acquaintances", "ACQUAINTANCE"),
                        ],
                        max_length=100,
                    ),
                ),
                ("details", models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name="person",
            name="family",
        ),
        migrations.DeleteModel(
            name="Family",
        ),
        migrations.AddField(
            model_name="relationship",
            name="people",
            field=models.ManyToManyField(
                related_name="relationships", to="village_api.Person"
            ),
        ),
    ]
