# Generated by Django 3.2.6 on 2021-08-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_api", "0004_auto_20210815_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="family_name",
            field=models.CharField(default="abc", max_length=256),
            preserve_default=False,
        ),
    ]
