# Generated by Django 3.2.6 on 2021-08-29 20:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_api", "0005_person_family_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="siblings",
        ),
        migrations.AddField(
            model_name="person",
            name="siblings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=list, size=None
            ),
        ),
    ]
