# Generated by Django 3.2.6 on 2021-08-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("village_api", "0006_auto_20210829_2150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationship",
            name="people",
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_api.person",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_api.relationship",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relationship",
            name="people",
            field=models.ManyToManyField(
                through="village_api.Relation", to="village_api.Person"
            ),
        ),
    ]
