# Generated by Django 3.2.6 on 2021-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_api", "0007_auto_20210830_1327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="people",
            field=models.ManyToManyField(
                related_name="relationships",
                through="village_api.Relation",
                to="village_api.Person",
            ),
        ),
    ]
